version: "3.9"
services:
  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - ./config:/data/config
      - ./data:/data/db
      - ./init/:/scripts/
    restart: always
    entrypoint: ["/usr/bin/mongod", "--port","27017", "--config", "/data/config/mongodb.conf"]
    extra_hosts:
      - mongo.example.com:127.0.0.1
    healthcheck:
      test: ["CMD", "/scripts/init.sh"]
      interval: 30s
      timeout: 10s
      start_period: 30s