spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/upload-files
logging:
  level:
    root: info
dev:
  xethh:
    tools:
      file-uploader:
        pubsub:
          url: tcps://mr5j7axd0ewnx.messaging.solace.cloud:55443
          un: solace-cloud-client
          pwd: q84fd5262lnd5lci1obs7keqef
          vpn: test-service
