name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Set Build ID
      run: echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV
    - name: "Show Build ID"
      run: echo "${BUILD_ID}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag file-upload-tools:$(date +%s)
    - name: Rename to latest
      run: docker image tag file-upload-tools:$(date +%s) file-upload-tools:latest
